---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-auto-github-gitops-config-1
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/darkowlzz/gitops-config-1.git

